import DemoShell from "../../components/DemoShell";
import { Instagram, Star } from "../../components/Icons";

const products = [
  { name: "Iyola Ankara Set", type: "Ankara", image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=80" },
  { name: "Adaeze Midi", type: "Ready-to-Wear", image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=800&q=80" },
  { name: "Nneka Kaftan", type: "Traditional Wear", image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80" },
  { name: "Zuri Gold Hoops", type: "Accessories", image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80" },
];

export default function FashionDemo() {
  return <DemoShell name="ZURI" eyebrow="Modern African fashion" description="A visual showcase for a fictional independent fashion label, designed around beautiful products, clear categories, and simple WhatsApp enquiries." image="https://images.unsplash.com/photo-1605763240000-7e93b172d754?auto=format&fit=crop&w=1400&q=85" color="#9a3f2d" whatsappText="Hello Zuri Fashion demonstration! I would like to ask about this collection." heroTitle={<>Made with identity.<br /><em>Worn with pride.</em></>}>
    <section className="demo-section collection-intro" id="services"><div className="container"><div className="demo-section-head"><span>The featured collection</span><h2>Made for every kind of moment.</h2><p>Four demonstration pieces inspired by texture, movement, and modern African style. Product names, availability, and ordering would be configured for a real brand.</p></div><div className="category-pills">{["Ankara", "Ready-to-Wear", "Traditional Wear", "Accessories"].map((item, i) => <span className={i === 0 ? "active" : ""} key={item}>{item}</span>)}</div><div className="product-grid">{products.map(product => <article key={product.name}><div><img loading="lazy" src={product.image} alt={`${product.name}, fictional demonstration product`} /><span>{product.type}</span></div><h3>{product.name}</h3><p>Enquire on WhatsApp</p></article>)}</div><p className="demo-disclaimer center">All products and brand details in this website are fictional demonstration content.</p></div></section>
    <section className="demo-section fashion-story" id="about"><div className="container story-grid"><div><span className="demo-label">The Zuri story</span><h2>Colour, culture,<br />and everyday beauty.</h2></div><div><p>Zuri is a fictional concept created to demonstrate how an emerging fashion label can present its point of view online without a complicated catalogue system.</p><p>The final business website would feature the founder’s real story, verified policies, available sizes, and direct ordering details.</p><a href="#contact">Meet the brand →</a></div></div></section>
    <section className="demo-section values-band"><div className="container values-grid">{["Small-batch concept", "Made to be touched", "Style without noise"].map((title, i) => <article key={title}><span>0{i + 1}</span><h3>{title}</h3><p>Part of the fictional Zuri brand story and visual direction.</p></article>)}</div></section>
    <section className="demo-section social-section" id="contact"><div className="container social-inner"><div><span className="demo-label">Follow the story</span><h2>See the collection in a different light.</h2><p>Sample social links below are inactive because this is a fictional portfolio demo.</p></div><div className="social-card"><Instagram /><div><strong>@zurifashion.demo</strong><span>Sample Instagram profile</span></div><span>→</span></div><div className="social-proof"><span><Star /><Star /><Star /><Star /><Star /></span><p>Sample presentation only — not a verified customer rating.</p></div></div></section>
    <section className="order-banner"><div className="container"><div><span>Zuri Fashion · Demonstration</span><h2>Found your style?</h2><p>Ask about sizes, colours, availability, and ordering.</p></div><a href="#contact">Start a WhatsApp enquiry →</a></div></section>
  </DemoShell>;
}
