import DemoShell from "../../components/DemoShell";
import { Check, MapPin } from "../../components/Icons";

const properties = [
  { title: "The Emerald Residence", type: "3 bedroom apartment", price: "Price on request", image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80", details: ["3 beds", "2 baths", "120 m²"] },
  { title: "Palm Grove Duplex", type: "4 bedroom duplex", price: "Price on request", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80", details: ["4 beds", "4 baths", "210 m²"] },
  { title: "Horizon Plot", type: "Residential land", price: "Price on request", image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1000&q=80", details: ["600 m²", "Serviced", "Title verified"] },
];

export default function RealEstateDemo() {
  return <DemoShell name="PRIMENEST" eyebrow="Property, thoughtfully presented" description="A polished demonstration for a fictional real-estate brand, focused on property discovery, useful listing details, and direct agent enquiries." image="https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=85" color="#203d50" whatsappText="Hello PrimeNest demonstration! I would like information about a property." heroTitle={<>Find your place<br /><em>in the future.</em></>}>
    <section className="demo-section property-intro" id="services"><div className="container"><div className="demo-section-head"><span>Featured opportunities</span><h2>A considered selection of spaces.</h2><p>The following properties are fictional demonstration listings and are not available for sale.</p></div><div className="property-grid">{properties.map(property => <article key={property.title}><div className="property-image"><img loading="lazy" src={property.image} alt={`${property.title}, fictional property listing`} /><span>Fictional listing</span></div><div className="property-body"><small>{property.type}</small><h3>{property.title}</h3><strong>{property.price}</strong><div>{property.details.map(item => <span key={item}>{item}</span>)}</div><a href="#contact">View details →</a></div></article>)}</div></div></section>
    <section className="demo-section property-about" id="about"><div className="container property-about-grid"><div className="property-large-image"><img loading="lazy" src="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80" alt="Contemporary fictional property interior" /></div><div><span className="demo-label">A better property experience</span><h2>Details first.<br />Distractions never.</h2><p>This fictional PrimeNest demonstration shows how a real estate business can present its proposition and make enquiries easy on a phone.</p><ul>{["Clear, image-led listings", "Details presented at a glance", "Direct agent conversations", "Mobile-first property discovery"].map(item => <li key={item}><Check />{item}</li>)}</ul></div></div></section>
    <section className="demo-section location-section"><div className="map-pattern"><div className="map-pin"><MapPin /><span>PrimeNest<br />Demonstration area</span></div></div><div className="container location-copy"><span className="demo-label">Local knowledge</span><h2>Find the right place to call home.</h2><p>Property searches are personal. A real business website would connect buyers and renters with verified listings, accurate locations, and a qualified agent.</p><a className="demo-big-button" href="#contact">Speak with an agent →</a></div></section>
    <section className="agent-section" id="contact"><div className="container agent-card"><div className="agent-avatar">AM<span>Sample agent</span></div><div><span>Your demonstration contact</span><h2>Ask Amina about a property.</h2><p>A real listing would include a verified agent name, direct contact details, office location, and response hours.</p></div><a href="#contact">Contact agent →</a></div></section>
  </DemoShell>;
}
